import Head from 'next/head'
import Board from '../components/Board'
import Layout from '../components/Layout'

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Board />
      </Layout>

      <footer>

      </footer>
    </div>
  )
}
